### ISSUE TITLE
luna_pinyin_ziam_tuan.dict 的用途

### ISSUE THREAD

**Issue by lazywei** [rime-aca/dictionaries#2]
請問一下，這個 repo 中有

```
luna_pinyin_ziam_tuan.dict
```

但是在 bintray 下載的詞庫中並沒有這個檔案，請問這個資料夾的用途是什麼？
謝謝！

**Comment by Patricivs** [comment]
這個是區分尖團（如尖 ziam 間 gian）的明月拼音詞庫，暫時未在bintray上發佈。

使用方法如下

將該資料夾下所有文件複製到用戶文件夾，並將下列內容添加入luna_pinyin.custom.yaml即可

 

patch:

  "translator/dictionary": luna_pinyin_ziam_tuan.extended

**Comment by lazywei** [comment]
理解，感謝！
