### ISSUE TITLE
正在找开源词库 这里的词库有版权问题吗

### ISSUE THREAD

**Issue by safetychinese** [rime-aca/dictionaries#8]
想在自己弄的输入方案dict里加入高频词库并开源出来，就考虑到版权的问题。
比如 luna_pinyin.extended.dict里写的：
 Thanks to the following works:
 * 新酷音共享詞庫
   Google搜尋獲得，由臺灣网友整理
 * 詞庫网
   http://baseterm.com/

都允许我们自由复制修改传播吧？
还有权重/频率怎么都是1？

**Comment by kunki** [comment]
以上詞庫都是通過公開途徑獲得的，但是由於一些來源沒有提供開源許可證，所以授權方式不明確。在徵詢作者意見之前最好不要公開散佈。

權重問題：這些詞彙都是不帶權重的。但是爲了與rime的詞彙適配，詞頻都改成了1。因爲默認詞頻是0，會與rime詞庫中的生僻詞同詞頻。改成1的目的正是爲了讓這些詞彙都排在詞頻爲0的系統生僻詞前面。

**Comment by safetychinese** [comment]
明白，谢啦。
